apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nodeapp
  name: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nodeapp
  template:
    metadata:
      labels:
        run: nodeapp
    spec:
      containers:
      - image: gcr.io/<google-project-id>/nodeapp:latest
        name: nodeapp
        ports:
        - containerPort: <container-port>
