apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
    matchLabels:
      app: "nodeapp"
  replicas: 1
  template:
    metadata:
      labels:
        app: "nodeapp"
    spec:
      containers:
      - name: nodeapp
        image: gcr.io/docker-project-381316/nodeapp:latest
        ports:
        - containerPort: 8000
