apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  selector:
    matchLabels:
      run: nodeapp
  replicas: 2
  template:
    metadata:
      labels:
        run: nodeapp
    spec:
      containers:
      - name: nodeapp
        ports:
        - containerPort: 80
        command:
        - sh
        - -c
        - while true; do sleep 1; done
        image: gcr.io/docker-project-381316/nodeapp:latest
