apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nodeapp
  name: nodeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nodeapp
  template:
    metadata:
      labels:
        run: nodeapp
    spec:
      containers:
      - image: gcr.io/docker-project-381316/nodeapp:latest
        name: nodeapp
        ports:
          - containerPort: 9080
        resources:
          requests:
            cpu: 100m
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
