kind: Service
apiVersion: v1
metadata:
  name: nodeapp
spec:
  selector:
     run: nodeapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  initialDelaySeconds: 150
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 10
