kind: Service
apiVersion: v1
metadata:
  name: nodeapp
spec:
  selector:
     run: nodeapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  resources:
       limits:
         cpu: "1"
         memory: 1Gi
       requests:
         cpu: 100m
         memory: 256Mi
