# apiVersion: v1
# kind: Service
# metadata:
#   name: node-python-service
# spec:
#   selector:
#     app: nodeapp
#   ports:
#   - protocol: "TCP"
#     port: 9080
#     targetPort: 9080
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: nodeapp
  type: LoadBalancer
